export const properties = [
  {
    id: 1,
    title: "Luxury Villa in Beverly Hills",
    location: "Beverly Hills, CA, USA",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTE3veA7q8qO9TcL_vPWuHVUVixgG888MQGsQ&s",
    price: 2500000,
    description: "A beautiful 5-bedroom villa with a pool and stunning views.",
  },
  {
    id: 2,
    title: "Modern Apartment in New York",
    location: "Manhattan, NY, USA",
    image: "https://t4.ftcdn.net/jpg/03/70/64/43/360_F_370644357_MDF4UXLAXTyyi2OyuK66tWW9cA2f8svL.jpg",
    price: 1200000,
    description: "A stylish 2-bedroom apartment in the heart of Manhattan.",
  },
  {
    id: 3,
    title: "Beach House in Malibu",
    location: "Malibu, CA, USA",
    image: "https://t4.ftcdn.net/jpg/00/98/30/93/360_F_98309392_LcMJtLXZMLLa9pdpuzwrY4MiwnihI2QT.jpg",
    price: 5000000,
    description:
      "A stunning beach house with private beach access and ocean views.",
  },
  {
    id: 4,
    title: "Cozy Cottage in Aspen",
    location: "Aspen, CO, USA",
    image: "https://images.posarellivillas.com/website_static/11/custom/xwide-asra16:9/home-med-1.jpg",
    price: 850000,
    description: "A charming 3-bedroom cottage perfect for winter getaways.",
  },
  {
    id: 5,
    title: "Penthouse in Downtown Miami",
    location: "Miami, FL, USA",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrZApafZeykycXoDcoicC8v9_MN3EM3YZROw&s",
    price: 3200000,
    description: "A luxurious 4-bedroom penthouse with ocean views.",
  },
  {
    id: 6,
    title: "Family Home in Houston",
    location: "Houston, TX, USA",
    image: "https://media.graphassets.com/kcqbCpucTbmzbM5yqelI",
    price: 600000,
    description: "A spacious 5-bedroom home in a family-friendly neighborhood.",
  },
  {
    id: 7,
    title: "Ranch in Dallas",
    location: "Dallas, TX, USA",
    image: "https://www.casagrand.co.in/wp-content/uploads/2021/10/phase-2-banner-thumb-1.jpg?ver=1.201",
    price: 950000,
    description:
      "A beautiful 6-acre ranch with modern amenities and open space.",
  },
  {
    id: 8,
    title: "Skyscraper Condo in Chicago",
    location: "Chicago, IL, USA",
    image: "https://www.cvvillas.com/dynamic-images/17000-17999/17190/17190_c=(0,1,5315,3540)_w=1366_h=910.webp?v=202405071552",
    price: 1400000,
    description: "A modern 2-bedroom condo on the 35th floor with city views.",
  },
  {
    id: 9,
    title: "Mountain Cabin in Colorado Springs",
    location: "Colorado Springs, CO, USA",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoj0ZG-589nsUnX3pyzKVkSdPFmBmqiV-UtA&s",
    price: 780000,
    description: "A cozy 2-bedroom cabin surrounded by beautiful mountains.",
  },
  {
    id: 10,
    title: "Historic Townhouse in Boston",
    location: "Boston, MA, USA",
    image: "https://www.thethinkingtraveller.com/Media/%2Fresized%2Fgreece%20villas%2Fenyalos%2Fmar22%2F1920%2Fttt_cyclades_islands_tinos_enyalos_mar22_018.jpg",
    price: 1800000,
    description:
      "A restored 4-bedroom historic townhouse in the heart of Boston.",
  },
];
